name: Dispatch events

on:
  push:
    branches: [ master ]
    paths:
      - '**.md'
      - '!README.md'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: anansi-project/anansi-project.github.io
          event-type: opds-push